spring:
  application:
    name: dubbo-provider
dubbo:
  scan:
    # 配置扫描包，路径是提供服务的实现类所在包
    base-packages: org.example.dubbo.provider.api
  registry:
    address: zookeeper://116.85.33.111:2181
    timeout: 15000
  protocols:
    dubbo:
      name: dubbo
      port: 12345
    hessian:
      name: hessian
      port: 22345
  application:
    shutwait: 15000
  protocol:
    accesslog: true
server:
  port: 8081
